/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oecd;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

public class Feedback extends javax.swing.JFrame {

    public Feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_feedback = new javax.swing.JPanel();
        jL_name = new javax.swing.JLabel();
        jTF_subject = new javax.swing.JTextField();
        jL_email = new javax.swing.JLabel();
        jTF_fromEmail = new javax.swing.JTextField();
        jL_subject = new javax.swing.JLabel();
        jTF_toEmail = new javax.swing.JTextField();
        jL_context = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_context = new javax.swing.JTextArea();
        jL_feedback = new javax.swing.JLabel();
        jBtn_back = new javax.swing.JButton();
        jBtn_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_name.setText("From Email:");

        jTF_subject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jL_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_email.setText("To Email: ");

        jTF_fromEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jL_subject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_subject.setText("Subject:");

        jTF_toEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jL_context.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_context.setText("Context:");

        jTA_context.setColumns(20);
        jTA_context.setRows(5);
        jScrollPane1.setViewportView(jTA_context);

        jL_feedback.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jL_feedback.setText("Feedback");

        jBtn_back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_back.setText("Back");
        jBtn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_backActionPerformed(evt);
            }
        });

        jBtn_submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_submit.setText("Submit");
        jBtn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_feedbackLayout = new javax.swing.GroupLayout(jP_feedback);
        jP_feedback.setLayout(jP_feedbackLayout);
        jP_feedbackLayout.setHorizontalGroup(
            jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_feedbackLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_toEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_fromEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
            .addGroup(jP_feedbackLayout.createSequentialGroup()
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_feedbackLayout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jL_feedback))
                    .addGroup(jP_feedbackLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_email)
                            .addComponent(jL_name)
                            .addComponent(jL_subject)
                            .addComponent(jL_context))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_feedbackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jP_feedbackLayout.setVerticalGroup(
            jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_feedbackLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jL_feedback)
                .addGap(18, 18, 18)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_fromEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_name))
                .addGap(18, 18, 18)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_toEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_email))
                .addGap(18, 18, 18)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_subject))
                .addGap(18, 18, 18)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_context)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jP_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_back)
                    .addComponent(jBtn_submit))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_backActionPerformed
        // TODO add your handling code here:
        dispose();
        Companies companies = new Companies();
        companies.setTitle("User Home Page");
        companies.setLocationRelativeTo(null); //center the form
        companies.setVisible(true);
    }//GEN-LAST:event_jBtn_backActionPerformed

    private void jBtn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_submitActionPerformed
        // TODO add your handling code here:
        String fromEmail = jTF_fromEmail.getText();
        String fromEmailPassword = "";
        String toEmail = jTF_toEmail.getText();
        String subject = jTF_subject.getText();
        String comment = jTA_context.getText();
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.auth", "");
        
        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator(){
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(fromEmail, fromEmailPassword);
            }
        });
        
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
            message.setSubject(subject);
            message.setText(jTA_context.getText());
            Transport.send(message);
        }catch(Exception ex){
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_jBtn_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_back;
    private javax.swing.JButton jBtn_submit;
    private javax.swing.JLabel jL_context;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_feedback;
    private javax.swing.JLabel jL_name;
    private javax.swing.JLabel jL_subject;
    private javax.swing.JPanel jP_feedback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_context;
    private javax.swing.JTextField jTF_fromEmail;
    private javax.swing.JTextField jTF_subject;
    private javax.swing.JTextField jTF_toEmail;
    // End of variables declaration//GEN-END:variables
}
