/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oecd;

import javax.swing.*;
import java.awt.*;  
import java.awt.event.*;  
import java.lang.Exception;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Registration extends javax.swing.JFrame {

    /* Creates new form Registration */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_registration = new javax.swing.JPanel();
        jL_Registration = new javax.swing.JLabel();
        jTF_firstName = new javax.swing.JTextField();
        jTF_lastName = new javax.swing.JTextField();
        jTF_IC = new javax.swing.JTextField();
        jTF_contactNo = new javax.swing.JTextField();
        jTF_email = new javax.swing.JTextField();
        jBtn_signUp = new javax.swing.JButton();
        jP_password = new javax.swing.JPasswordField();
        jP_cPassword = new javax.swing.JPasswordField();
        jBtn_signIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_registration.setMinimumSize(new java.awt.Dimension(0, 0));
        jP_registration.setPreferredSize(new java.awt.Dimension(1020, 620));
        jP_registration.setRequestFocusEnabled(false);

        jL_Registration.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jL_Registration.setText("Registration");

        jTF_firstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_lastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_lastNameActionPerformed(evt);
            }
        });

        jTF_IC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_contactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_emailActionPerformed(evt);
            }
        });

        jBtn_signUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_signUp.setText("Submit");
        jBtn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_signUpActionPerformed(evt);
            }
        });

        jP_cPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jP_cPasswordActionPerformed(evt);
            }
        });

        jBtn_signIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_signIn.setText("Sign In");
        jBtn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_signInActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("IC/Passport:");

        jLabel4.setText("Contact Number:");

        jLabel5.setText("Email:");

        jLabel6.setText("Password:");

        jLabel7.setText("Confirm Password:");

        javax.swing.GroupLayout jP_registrationLayout = new javax.swing.GroupLayout(jP_registration);
        jP_registration.setLayout(jP_registrationLayout);
        jP_registrationLayout.setHorizontalGroup(
            jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_registrationLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_Registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_firstName)
                    .addComponent(jTF_lastName)
                    .addComponent(jTF_IC)
                    .addComponent(jTF_contactNo)
                    .addComponent(jTF_email)
                    .addComponent(jP_password)
                    .addComponent(jP_cPassword)
                    .addGroup(jP_registrationLayout.createSequentialGroup()
                        .addComponent(jBtn_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_signIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jP_registrationLayout.setVerticalGroup(
            jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_registrationLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jL_Registration)
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_IC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jP_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jP_cPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jP_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_signUp)
                    .addComponent(jBtn_signIn))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cancel Button Action Performed
    //required???
    private void jBtn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_signInActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setTitle("Sign In");
        login.setLocationRelativeTo(null); //center the form
        login.setVisible(true);

        /*
        //second example
        this.toBack();
        setVisible(false);
        new Login().toFront();
        new Login().setState(java.awt.Frame.NORMAL);

        //first example
        Login login = new JFrame("Login");
        Login login = new Login();
        login.setVisible(true);
        login.toFront();
        */
    }//GEN-LAST:event_jBtn_signInActionPerformed

    //Sign Up Button Action Performed
    private void jBtn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_signUpActionPerformed
        // TODO add your handling code here:

        //second example
        String fname = jTF_firstName.getText();
        String lname = jTF_lastName.getText();
        String ic = jTF_IC.getText();
        String contact = jTF_contactNo.getText();
        String email = jTF_email.getText();
        String password = String.valueOf(jP_password.getPassword());
        String c_password = String.valueOf(jP_cPassword.getPassword());

        if(fname.isEmpty() || lname.isEmpty() || ic.isEmpty() || contact.isEmpty() || email.isEmpty() || password.isEmpty() || c_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill up the form", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (password != c_password) {
            JOptionPane.showMessageDialog(this, "Password does not match", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //start the registration/sign up process.
            userRegister(fname, lname, ic, contact, email, password, c_password);
        }
    }//GEN-LAST:event_jBtn_signUpActionPerformed

    private void jTF_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_emailActionPerformed

    private void jTF_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_lastNameActionPerformed

    private void jP_cPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jP_cPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_signIn;
    private javax.swing.JButton jBtn_signUp;
    private javax.swing.JLabel jL_Registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jP_cPassword;
    private javax.swing.JPasswordField jP_password;
    private javax.swing.JPanel jP_registration;
    private javax.swing.JTextField jTF_IC;
    private javax.swing.JTextField jTF_contactNo;
    private javax.swing.JTextField jTF_email;
    private javax.swing.JTextField jTF_firstName;
    private javax.swing.JTextField jTF_lastName;
    // End of variables declaration//GEN-END:variables

    /*check email*/
    private void userRegister(String fname, String lname, String ic, String contact, String email, String password, String c_password) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //JOptionPane.showMessageDialog(null, "This Username Already Exist");
        
        Connection conn = DBConnection.connectDB();
        if(conn != null){
            try {
            PreparedStatement pst = (PreparedStatement)conn.prepareStatement("INSERT INTO user(fname, lname, ic, contact, email, password) VALUES(?,?,?,?,?,?)");
            //PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, fname);
            pst.setString(2, lname);
            pst.setString(3, ic);
            pst.setString(4, contact);
            pst.setString(5, email);
            pst.setString(6, password);
            //pst.setString(1, jTF_email.getText());
            //pst.setString(2, jP_password.getPassword().toString());
            
            int res = pst.executeUpdate();
            /*
                dispose();
                Login login = new Login();
                login.setTitle("Login");
                login.setVisible(true);
                //setVisible(false);
            */
            JOptionPane.showMessageDialog(this, "User data inserted", "Success", JOptionPane.INFORMATION_MESSAGE);  
            
            jTF_firstName.setText("");
            jTF_lastName.setText("");
            jTF_IC.setText("");
            jTF_contactNo.setText("");
            jTF_email.setText("");
            jP_password.setText("");
            jP_cPassword.setText("");
            
            //throw new UnsupportedOperationException("Not supported yet.");
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("There connection is not available");
        }
    }
}
