/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oecd;

import javax.swing.JOptionPane;

public class User extends javax.swing.JFrame {

    /* Creates new form User */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_user = new javax.swing.JPanel();
        jL_welcome = new javax.swing.JLabel();
        jBtn_company = new javax.swing.JButton();
        jBtn_signOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_welcome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jL_welcome.setText("Welcome!");

        jBtn_company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_company.setText("List of Companies");
        jBtn_company.setBorderPainted(false);
        jBtn_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_companyActionPerformed(evt);
            }
        });

        jBtn_signOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_signOut.setText("Sign Out");
        jBtn_signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_signOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_userLayout = new javax.swing.GroupLayout(jP_user);
        jP_user.setLayout(jP_userLayout);
        jP_userLayout.setHorizontalGroup(
            jP_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_userLayout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addGroup(jP_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_signOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jP_userLayout.setVerticalGroup(
            jP_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_userLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jL_welcome)
                .addGap(18, 18, 18)
                .addComponent(jBtn_company)
                .addGap(18, 18, 18)
                .addComponent(jBtn_signOut)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_signOutActionPerformed
        // TODO add your handling code here:
        int response =  JOptionPane.showConfirmDialog(jBtn_signOut, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                // JOptionPane.setRootFrame(null);
                if (response == JOptionPane.YES_OPTION) {
                    dispose();
                    Login login = new Login();
                    login.setTitle("Sign In");
                    login.setLocationRelativeTo(null); //center the form
                    login.setVisible(true);
                }else{
                    dispose();
                    User user = new User();
                    user.setTitle("User Home Page");
                    user.setLocationRelativeTo(null); //center the form
                    user.setVisible(true);
                }
    }//GEN-LAST:event_jBtn_signOutActionPerformed

    private void jBtn_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_companyActionPerformed
        // TODO add your handling code here:
        dispose();
        CompanyList companies = new CompanyList();
        companies.setTitle("Company List");
        companies.setLocationRelativeTo(null); //center the form
        companies.setVisible(true);
    }//GEN-LAST:event_jBtn_companyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_company;
    private javax.swing.JButton jBtn_signOut;
    private javax.swing.JLabel jL_welcome;
    private javax.swing.JPanel jP_user;
    // End of variables declaration//GEN-END:variables

}
